trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Install Terraform
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

# Terraform Init, Format, Validate and Plan
- task: AzureCLI@2
  displayName: 'Terraform Init, Validate and Plan'
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

    inlineScript: |
      terraform init
      terraform fmt -check
      terraform validate
      terraform plan